FROM openhs/ubuntu-nvidia

# put instructions for installing desired GUI application here
# ...

RUN apt-get update && apt-get install -y xterm x11-apps

CMD ["/usr/bin/xclock"]
#CMD ["/usr/bin/xterm"]
